# SSH creds for all hosts (PLAINTEXT FOR DEMO â€” use ansible-vault in real life)
ansible_user: ansible
ansible_password: Labl@b1234
ansible_connection: ssh
# If sudo is ever needed:
# ansible_become: true
# ansible_become_method: sudo
# ansible_become_password: demo_password


# Destination to trace to (can be overridden with -e "netpath_destination=1.1.1.1")
netpath_destination: 10.200.200.200
#netpath_destination: 8.8.8.8

# Nautobot vars
nautobot_url: "http://192.168.100.10:8085"
nautobot_token: "0123456789abcdef0123456789abcdef01234567"
nautobot_namespace: "Global"
nautobot_validate_certs: false
nautobot_depth: 2

nautobot_enrich_artifacts_dir: "./artifacts"

nautobot_enrich_include:
  device_name: true
  interface_name: true
  device_id: false
  interface_id: false
  # site_name: true   # example if you add it